# Generated by Django 5.0.4 on 2024-04-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gameadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gameadmin',
        ),
    ]
