# Generated by Django 5.0.4 on 2024-04-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_gameadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price_off',
            field=models.IntegerField(null=True),
        ),
    ]
